import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Music, Send, Loader2, Sparkles, Play, Youtube, Heart, History, Trash2, Share2, Info } from 'lucide-react';
import { analyzeVibe, type VibeAnalysis, type SongRecommendation } from './lib/gemini';
import { cn } from './lib/utils';

export default function App() {
  const [input, setInput] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [vibe, setVibe] = useState<VibeAnalysis | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [favorites, setFavorites] = useState<SongRecommendation[]>([]);
  const [history, setHistory] = useState<VibeAnalysis[]>([]);
  const [showFavorites, setShowFavorites] = useState(false);
  const [isSpotifyAuthed, setIsSpotifyAuthed] = useState(false);
  const [isCreatingPlaylist, setIsCreatingPlaylist] = useState(false);

  // Load favorites and history from localStorage
  useEffect(() => {
    const savedFavs = localStorage.getItem('vibesync_favorites');
    const savedHistory = localStorage.getItem('vibesync_history');
    if (savedFavs) setFavorites(JSON.parse(savedFavs));
    if (savedHistory) setHistory(JSON.parse(savedHistory));
    
    checkSpotifyAuth();
  }, []);

  const checkSpotifyAuth = async () => {
    try {
      const res = await fetch('/api/auth/spotify/me');
      const data = await res.json();
      setIsSpotifyAuthed(data.authenticated);
    } catch (err) {
      console.error('Failed to check Spotify auth:', err);
    }
  };

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data?.type === 'SPOTIFY_AUTH_SUCCESS') {
        setIsSpotifyAuthed(true);
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, []);

  const handleSpotifyConnect = async () => {
    try {
      const res = await fetch('/api/auth/spotify/url');
      const { url } = await res.json();
      window.open(url, 'spotify_auth', 'width=600,height=700');
    } catch (err) {
      console.error('Failed to get Spotify auth URL:', err);
    }
  };

  const handleCreatePlaylist = async () => {
    if (!vibe) return;
    if (!isSpotifyAuthed) {
      handleSpotifyConnect();
      return;
    }

    setIsCreatingPlaylist(true);
    try {
      const res = await fetch('/api/spotify/create-playlist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: `VibeSync: ${vibe.explanation.slice(0, 50)}`,
          description: `Curated vibe: ${vibe.explanation}. Generated by VibeSync AI.`,
          songs: vibe.recommendations
        })
      });

      const data = await res.json();
      if (data.success) {
        window.open(data.playlistUrl, '_blank');
      } else {
        throw new Error(data.error || 'Failed to create playlist');
      }
    } catch (err: any) {
      console.error(err);
      alert(err.message || 'Failed to create playlist. Please try again.');
    } finally {
      setIsCreatingPlaylist(false);
    }
  };

  // Save favorites and history to localStorage
  useEffect(() => {
    localStorage.setItem('vibesync_favorites', JSON.stringify(favorites));
  }, [favorites]);

  useEffect(() => {
    localStorage.setItem('vibesync_history', JSON.stringify(history));
  }, [history]);

  const handleAnalyze = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isAnalyzing) return;

    setIsAnalyzing(true);
    setError(null);
    try {
      const analyzedVibe = await analyzeVibe(input);
      setVibe(analyzedVibe);
      setHistory(prev => [analyzedVibe, ...prev].slice(0, 10));
      setShowFavorites(false);
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Something went wrong. Please try again.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const toggleFavorite = (song: SongRecommendation) => {
    setFavorites(prev => {
      const isFav = prev.some(f => f.title === song.title && f.artist === song.artist);
      if (isFav) {
        return prev.filter(f => !(f.title === song.title && f.artist === song.artist));
      }
      return [...prev, song];
    });
  };

  const isFavorite = (song: SongRecommendation) => {
    return favorites.some(f => f.title === song.title && f.artist === song.artist);
  };

  const getYTMusicLink = (song: SongRecommendation) => {
    const query = encodeURIComponent(`${song.title} ${song.artist}`);
    return `https://music.youtube.com/search?q=${query}`;
  };

  const getSpotifySearchLink = (song: SongRecommendation) => {
    const query = encodeURIComponent(`${song.title} ${song.artist}`);
    return `https://open.spotify.com/search/${query}`;
  };

  const shareVibe = () => {
    if (!vibe) return;
    const text = `Check out my current vibe on VibeSync: "${vibe.explanation}"\n\nRecommended songs:\n${vibe.recommendations.map(s => `- ${s.title} by ${s.artist}`).join('\n')}`;
    if (navigator.share) {
      navigator.share({ title: 'VibeSync', text });
    } else {
      navigator.clipboard.writeText(text);
      alert('Vibe copied to clipboard!');
    }
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2
      }
    },
    exit: {
      opacity: 0,
      transition: { staggerChildren: 0.05, staggerDirection: -1 }
    }
  };

  const itemVariants = {
    hidden: { y: 40, opacity: 0, scale: 0.95, filter: 'blur(10px)' },
    visible: { 
      y: 0, 
      opacity: 1, 
      scale: 1, 
      filter: 'blur(0px)',
      transition: { type: 'spring' as const, damping: 25, stiffness: 100 }
    },
    exit: { 
      y: -20, 
      opacity: 0, 
      scale: 0.95, 
      filter: 'blur(10px)',
      transition: { duration: 0.4 }
    }
  };

  return (
    <div className="min-h-screen relative overflow-hidden font-sans text-white selection:bg-primary/30 bg-surface">
      <div className="grain" />
      
      {/* Dynamic Background */}
      <div 
        className="fixed inset-0 transition-colors duration-1000 ease-in-out -z-10"
        style={{ 
          backgroundColor: vibe?.vibeColor ? `${vibe.vibeColor}08` : '#0f0d16',
          backgroundImage: `radial-gradient(circle at 50% 50%, ${vibe?.vibeColor || '#f183ff'}15 0%, transparent 70%)`
        }} 
      />
      <div className="atmosphere fixed inset-0 pointer-events-none" />
      
      {/* Floating Navigation Dock */}
      <div className="fixed bottom-8 left-1/2 -translate-x-1/2 z-50">
        <nav className="glass-panel px-6 py-3 rounded-full flex items-center gap-6 shadow-[0_20px_50px_rgba(0,0,0,0.5)]">
          <div className="flex items-center gap-2 cursor-pointer group" onClick={() => { setVibe(null); setShowFavorites(false); }}>
            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary to-primary-dim flex items-center justify-center group-hover:scale-110 transition-transform">
              <Music className="w-4 h-4 text-surface" />
            </div>
            <span className="text-lg font-display font-bold tracking-tight hidden sm:block">VibeSync</span>
          </div>
          
          <div className="w-px h-6 bg-outline-variant/20" />
          
          <div className="flex items-center gap-2">
            {!isSpotifyAuthed && (
              <button 
                onClick={handleSpotifyConnect}
                className="flex items-center gap-2 px-4 py-2 rounded-full bg-secondary/10 text-secondary text-xs font-bold hover:bg-secondary hover:text-surface transition-all"
              >
                <Play className="w-3 h-3 fill-current" /> Connect
              </button>
            )}
            <button 
              onClick={() => setShowFavorites(!showFavorites)}
              className={cn(
                "p-2.5 rounded-full transition-all",
                showFavorites ? "bg-primary text-surface" : "hover:bg-surface-variant/40 text-white/60"
              )}
            >
              <Heart className={cn("w-5 h-5", showFavorites && "fill-current")} />
            </button>
            <button 
              className="p-2.5 rounded-full hover:bg-surface-variant/40 text-white/60 transition-all"
              onClick={() => vibe && shareVibe()}
            >
              <Share2 className="w-5 h-5" />
            </button>
          </div>
        </nav>
      </div>

      <main className="max-w-6xl mx-auto px-6 pt-20 pb-40 relative z-10">
        <AnimatePresence mode="wait">
          {!vibe && !showFavorites && (
            <motion.div
              key="hero"
              initial={{ opacity: 0, y: 30, filter: 'blur(10px)' }}
              animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
              exit={{ opacity: 0, y: -30, filter: 'blur(10px)' }}
              transition={{ duration: 1.2, ease: [0.22, 1, 0.36, 1] }}
              className="text-center md:text-left mb-16"
            >
              <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-surface-variant/30 text-[10px] uppercase tracking-[0.2em] font-bold text-primary mb-8">
                <Sparkles className="w-3 h-3" />
                <span>The Resonant Canvas</span>
              </div>
              <h1 className="text-7xl md:text-[8rem] font-display font-black tracking-[-0.04em] mb-12 leading-[1.1] text-white">
                What's your <br />
                <span className="text-primary italic font-light">vibe</span> today?
              </h1>
              <p className="text-xl text-white/40 max-w-xl font-light mb-12 leading-relaxed">
                Type how you feel, and we'll stitch together the perfect sonic landscape for your current state of mind.
              </p>

              <form onSubmit={handleAnalyze} className="relative max-w-2xl">
                <div className="relative group">
                  <input
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder="e.g. 'Late night drive through a neon city'"
                    className="w-full bg-surface-container-low border border-white/5 rounded-full px-10 py-8 text-xl focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all placeholder:text-white/30 text-white"
                  />
                  <div className="absolute inset-0 rounded-full pointer-events-none group-focus-within:shadow-[0_0_50px_rgba(241,131,255,0.15)] transition-shadow duration-500" />
                  <button
                    type="submit"
                    disabled={isAnalyzing || !input.trim()}
                    className="absolute right-3 top-1/2 -translate-y-1/2 p-5 rounded-full bg-gradient-to-br from-primary to-primary-dim text-surface disabled:opacity-20 transition-all shadow-lg shadow-primary/20 hover:scale-105 active:scale-95"
                  >
                    {isAnalyzing ? (
                      <Loader2 className="w-6 h-6 animate-spin" />
                    ) : (
                      <Send className="w-6 h-6" />
                    )}
                  </button>
                </div>
                {error && <p className="mt-4 text-tertiary text-sm font-medium">{error}</p>}
              </form>

              {history.length > 0 && (
                <div className="mt-20">
                  <h3 className="text-[10px] uppercase tracking-[0.3em] font-bold text-white/20 mb-8 flex items-center gap-3">
                    <History className="w-4 h-4" /> Recent Vibes
                  </h3>
                  <div className="flex flex-wrap gap-4">
                    {history.map((h, i) => (
                      <button
                        key={i}
                        onClick={() => setVibe(h)}
                        className="px-6 py-3 rounded-full bg-surface-container-low text-sm text-white/60 hover:bg-surface-container-high hover:text-white transition-all"
                      >
                        {h.explanation}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </motion.div>
          )}

          {showFavorites && (
            <motion.section
              key="favorites"
              variants={containerVariants}
              initial="hidden"
              animate="visible"
              exit="exit"
              className="space-y-16"
            >
              <motion.div variants={itemVariants} className="flex items-center justify-between">
                <h2 className="text-6xl font-display font-black tracking-tight">Your <span className="text-primary italic font-light">Collection</span></h2>
                <button 
                  onClick={() => setFavorites([])}
                  className="p-3 rounded-full bg-surface-variant/20 text-white/20 hover:text-tertiary transition-colors"
                  title="Clear all favorites"
                >
                  <Trash2 className="w-5 h-5" />
                </button>
              </motion.div>
              
              {favorites.length === 0 ? (
                <motion.div variants={itemVariants} className="py-32 text-center text-white/10">
                  <Heart className="w-24 h-24 mx-auto mb-8 stroke-[0.5]" />
                  <p className="text-2xl font-light italic">Your collection is empty. Heart some songs to save them!</p>
                </motion.div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
                  {favorites.map((song, i) => (
                    <SongCard 
                      key={i} 
                      song={song} 
                      isFav={true} 
                      onToggleFav={() => toggleFavorite(song)}
                      onSpotify={() => window.open(getSpotifySearchLink(song), '_blank')}
                      onYT={() => window.open(getYTMusicLink(song), '_blank')}
                      variants={itemVariants}
                    />
                  ))}
                </div>
              )}
            </motion.section>
          )}

          {vibe && !showFavorites && (
            <motion.section
              key="results"
              variants={containerVariants}
              initial="hidden"
              animate="visible"
              exit="exit"
              className="space-y-20"
            >
              <motion.div variants={itemVariants} className="relative p-16 card-organic glass-panel">
                <div 
                  className="absolute top-0 right-0 w-[500px] h-[500px] blur-[150px] rounded-full -mr-64 -mt-64 opacity-40 animate-pulse-glow"
                  style={{ backgroundColor: vibe.vibeColor }}
                />
                <div className="relative z-10">
                  <h2 className="text-[10px] uppercase tracking-[0.4em] font-bold text-white/30 mb-8 flex items-center gap-3">
                    <Sparkles className="w-4 h-4 text-primary" /> Current Vibe
                  </h2>
                  <p className="text-5xl md:text-8xl font-display font-black tracking-tighter italic mb-12 leading-[0.9]">"{vibe.explanation}"</p>
                  <div className="flex flex-wrap items-center gap-6">
                    <button 
                      onClick={() => setVibe(null)}
                      className="btn-secondary"
                    >
                      New Search
                    </button>
                    <button 
                      onClick={handleCreatePlaylist}
                      disabled={isCreatingPlaylist}
                      className="btn-primary flex items-center gap-3 disabled:opacity-50"
                    >
                      {isCreatingPlaylist ? (
                        <Loader2 className="w-5 h-5 animate-spin" />
                      ) : (
                        <Play className="w-5 h-5 fill-current" />
                      )}
                      {isSpotifyAuthed ? 'Create Spotify Playlist' : 'Connect Spotify'}
                    </button>
                    <button 
                      onClick={shareVibe}
                      className="p-4 rounded-full bg-surface-variant/30 hover:bg-surface-variant/50 transition-all text-white/60 hover:text-white"
                    >
                      <Share2 className="w-6 h-6" />
                    </button>
                  </div>
                </div>
              </motion.div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
                {vibe.recommendations.map((song, i) => (
                  <SongCard 
                    key={i} 
                    song={song} 
                    isFav={isFavorite(song)} 
                    onToggleFav={() => toggleFavorite(song)}
                    onSpotify={() => window.open(getSpotifySearchLink(song), '_blank')}
                    onYT={() => window.open(getYTMusicLink(song), '_blank')}
                    variants={itemVariants}
                  />
                ))}
              </div>
            </motion.section>
          )}
        </AnimatePresence>
      </main>

      <footer className="max-w-6xl mx-auto px-6 py-12 border-t border-white/5 flex flex-col md:flex-row justify-between items-center gap-6 text-white/20 text-sm font-light">
        <p>© 2026 VibeSync. Built with Gemini AI.</p>
        <div className="flex gap-8">
          <a href="#" className="hover:text-white transition-colors">Privacy</a>
          <a href="#" className="hover:text-white transition-colors">Terms</a>
          <a href="#" className="hover:text-white transition-colors">Contact</a>
        </div>
      </footer>
    </div>
  );
}

interface SongCardProps {
  song: SongRecommendation;
  isFav: boolean;
  onToggleFav: () => void;
  onSpotify: () => void;
  onYT: () => void;
  variants?: any;
}

function SongCard({ song, isFav, onToggleFav, onSpotify, onYT, variants }: SongCardProps) {
  return (
    <motion.div
      variants={variants}
      whileHover={{ 
        y: -10, 
        scale: 1.02,
        transition: { type: 'spring' as const, damping: 15, stiffness: 200 }
      }}
      className="group relative p-10 card-organic bg-surface-container-low hover:bg-surface-container-high transition-colors duration-500 flex flex-col liquid-shadow"
    >
      <div className="flex justify-between items-start mb-10">
        <div className="w-16 h-16 rounded-[1.5rem] bg-gradient-to-br from-primary to-primary-dim flex items-center justify-center shadow-[0_0_30px_rgba(241,131,255,0.2)] group-hover:scale-110 transition-transform duration-500">
          <Music className="w-8 h-8 text-surface" />
        </div>
        <div className="flex gap-2">
          <button 
            onClick={onToggleFav}
            className={cn(
              "p-4 rounded-2xl transition-all",
              isFav ? "bg-primary/20 text-primary" : "bg-surface-variant/20 text-white/20 hover:text-white hover:bg-surface-variant/40"
            )}
          >
            <Heart className={cn("w-6 h-6", isFav && "fill-current")} />
          </button>
        </div>
      </div>

      <div className="flex-1">
        <div className="flex flex-wrap gap-3 mb-6">
          {song.tags.map(tag => (
            <span key={tag} className="px-3 py-1 rounded-full bg-surface-variant/30 text-[9px] uppercase tracking-[0.2em] font-bold text-white/40">
              {tag}
            </span>
          ))}
        </div>
        <h3 className="text-3xl font-display font-black mb-2 group-hover:text-primary transition-colors leading-tight">{song.title}</h3>
        <p className="text-white/40 mb-8 font-light text-lg">{song.artist} {song.year && `• ${song.year}`}</p>
        
        <div className="relative p-6 rounded-3xl bg-surface-container-lowest mb-10">
          <Info className="absolute top-6 right-6 w-4 h-4 text-white/10" />
          <p className="text-sm text-white/60 italic leading-relaxed pr-6">
            "{song.reason}"
          </p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <button 
          onClick={onSpotify}
          className="flex items-center justify-center gap-3 py-5 rounded-full bg-secondary/10 text-secondary hover:bg-secondary hover:text-surface transition-all font-bold text-xs uppercase tracking-widest"
        >
          <Play className="w-4 h-4 fill-current" /> Spotify
        </button>
        <button 
          onClick={onYT}
          className="flex items-center justify-center gap-3 py-5 rounded-full bg-tertiary/10 text-tertiary hover:bg-tertiary hover:text-surface transition-all font-bold text-xs uppercase tracking-widest"
        >
          <Youtube className="w-4 h-4" /> YouTube
        </button>
      </div>
    </motion.div>
  );
}
